### PR TITLE
feat: jetzt unterschreiben

### PR DESCRIPTION
**Pull request by peterpeterparker**
According manu's design the text should be "Jetzt unterschreiben"

Notabene: not translated in french, "signer maintenant" sounds silly.

### CODE REVIEW

**Comment by sansan88** [comment]
what could make sense in french?

**Comment by peterpeterparker** [comment]
"signer l'initiative" would be a good call to action I think

**Comment by sansan88** [comment]
the "problem" is, we dont have always an initiative. Sometimes its a referendum.

**Comment by peterpeterparker** [comment]
that's why the text can be provided with a slot ;)

**Pull request merged**
